# Generated by Django 2.0.8 on 2018-11-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('SA_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.CharField(blank=True, max_length=30, null=True)),
                ('Number_of_suppliers', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Details_1', models.CharField(blank=True, max_length=50, null=True)),
                ('Details_2', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Category', models.CharField(default='신규등록', max_length=50)),
                ('Updated_date', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier1', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier1_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier1_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier1_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier1_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier2', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier2_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier2_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier2_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier2_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier3', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier3_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier3_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier3_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier3_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier4', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier4_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier4_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier4_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier4_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier5', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier5_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier5_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier5_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier5_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier6', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier6_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier6_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier6_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier6_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier7', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier7_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier7_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier7_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier7_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier8', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier8_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier8_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier8_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier8_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SA_No', models.IntegerField(blank=True, null=True)),
                ('DateTime', models.CharField(blank=True, max_length=50, null=True)),
                ('User', models.CharField(blank=True, max_length=30, null=True)),
                ('Field', models.CharField(blank=True, max_length=30, null=True)),
                ('Before', models.CharField(blank=True, max_length=50, null=True)),
                ('After', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
